name: Feature request
description: Suggest a new feature
title: '[Feature]: '
labels: ['feature']
body:
    - type: textarea
      attributes:
          label: Problem statement
          description: What problem does this solve?
      validations:
          required: true

    - type: textarea
      attributes:
          label: Proposed solution
          description: Your idea for solving it.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Alternatives considered
          description: Other options you thought about.
